#!/bin/bash
echo "📊 Verifying Database Contents"
echo "=============================="
echo ""
echo "Users:"
sqlite3 prisma/dev.db "SELECT email, name FROM User;"
echo ""
echo "Accounts:"
sqlite3 prisma/dev.db "SELECT sourceName, connected FROM Account;"
echo ""
echo "Transactions (first 5):"
sqlite3 prisma/dev.db "SELECT date, description, amount, type, category FROM Transaction ORDER BY date DESC LIMIT 5;"
echo ""
echo "Summary:"
echo "--------"
echo -n "Total Users: "
sqlite3 prisma/dev.db "SELECT COUNT(*) FROM User;"
echo -n "Total Accounts: "
sqlite3 prisma/dev.db "SELECT COUNT(*) FROM Account;"
echo -n "Total Transactions: "
sqlite3 prisma/dev.db "SELECT COUNT(*) FROM Transaction;"
